title: <p align="center"> L.A.D </p>

logo: "/images/VergilDMC.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://github.com/LAD2k3">GitHub</a>
  </p>
  
  <p align="justify">
  I am studying SoftWare Engineering at Sai Gon University.
  <br><br>
  I am currently learning AI and new programing techniques.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
